name: CI workflow

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Install pylint
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install pylint
     - name: Lint pylint
       run: |
         export PYTHONPATH=${PWD}
         pylint --fail-under=8 ${PWD}/src ${PWD}/tests
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit test
        run: |
          python -m pytest -vv
